networks:
  dev:

services:

  # api_server:
  #   build:
  #     context: ./api_server
  #   networks:
  #     - dev
  #   environment:
  #     - DATABASE_URL=postgresql://@aazatserver.ru:5432/nutrition_db
  #     - DATABASE_URL_async=postgresql+asyncpg://@aazatserver.ru:5432/nutrition_db

  #   volumes:
  #     - ./SQL:/SQL

  scale_server:
    build:
      context: ./scale_server
    networks:
      - dev

    environment:
      - PID=32452345
      - VOSK_LANG=ru
      - VOSK_SAMPLE_RATE=16000.0
      - MQTT_ADDRESS=aazatserver.ru
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=admin
      - TEST_FILE_NAME=test.wav
      - VOSK_MODEL_PATH=/vosk-model-small-ru-0.22
      - VOSK_MODEL_PATH2=/alphacep-model-android-ru-0.3
      - DATABASE_URL=postgresql://@aazatserver.ru:5432/nutrition_db
      - DATABASE_URL_async=postgresql+asyncpg://@aazatserver.ru:5432/nutrition_db
      - PYTHONUNBUFFERED=1
    # env_file:
    #   - .env
    volumes:
      - ./SQL:/SQL
      - ./scale_server/vosk-model-small-ru-0.22:/vosk-model-small-ru-0.22
      - ./scale_server/alphacep-model-android-ru-0.3:/alphacep-model-android-ru-0.3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - './nginx.conf:/etc/nginx/nginx.conf'
  #     - '/etc/letsencrypt:/etc/letsencrypt'
  #   depends_on:
  #     - api_server
  #     - scale_server
  #   networks:
  #     - dev

  # backend:
  #   build:
  #     context: ./backend
  #   networks:
  #     - dev

  # frontend:
  #   build:
  #     context: ./frontend
  #   networks:
  #     - dev