networks:
  dev:

services:

  api_server:
    build:
      context: ./api_server
    networks:
      - dev
    ports:
      - "8000:8000"
    env_file:
      - ./api_server/.env
      - ./SQL/.env.db
    volumes:
      - ./SQL:/SQL

  scale_server:
    build:
      context: ./scale_server
    networks:
      - dev
    ports:
      - "5000:5000"
    env_file:
      - ./SQL/.env.db
      - ./scale_server/.env.scale_server
    volumes:
      - ./SQL:/SQL
      - ./scale_server/vosk-model-small-ru-0.22:/vosk-model-small-ru-0.22
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - api_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - dev
    restart: always

# docker compose --profile certbot run --rm certbot certonly --webroot -w /var/www/certbot -d aazatserver.ru
  certbot:
    image: certbot/certbot
    profiles: ["certbot"]
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - dev
    command: > 
      certonly --webroot --webroot-path=/var/www/certbot
      --email atavlykaev@list.ru --agree-tos --no-eff-email
      -d aazatserver.ru
