networks:
  dev:

services:

  api_server:
    build:
      context: ./api_server
    networks:
      - dev
    environment:
      - DATABASE_URL=postgresql://@aazatserver.ru:5432/nutrition_db
      - DATABASE_URL_async=postgresql+asyncpg://@aazatserver.ru:5432/nutrition_db

    volumes:
      - ./SQL:/SQL

  scale_server:
    build:
      context: ./scale_server
    networks:
      - dev
    environment:
      - DATABASE_URL=postgresql://@aazatserver.ru:5432/nutrition_db
      - DATABASE_URL_async=postgresql+asyncpg://@aazatserver.ru:5432/nutrition_db
    volumes:
      - ./SQL:/app/SQL
    
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - api_server
      - scale_server
    networks:
      - dev

  # backend:
  #   build:
  #     context: ./backend
  #   networks:
  #     - dev

  # frontend:
  #   build:
  #     context: ./frontend
  #   networks:
  #     - dev