networks:
  dev:

services:

  # api_server:
  #   build:
  #     context: ./api_server
  #   networks:
  #     - dev
  #   environment:
  #     - DATABASE_URL=postgresql://@aazatserver.ru:5432/nutrition_db
  #     - DATABASE_URL_async=postgresql+asyncpg://@aazatserver.ru:5432/nutrition_db

  #   volumes:
  #     - ./SQL:/SQL

  scale_server:
    build:
      context: ./scale_server
    networks:
      - dev
    env_file:
      - .env
    volumes:
      - ./SQL:/app/SQL
      - ./vosk-model-small-ru-0.22:/app/vosk-model-small-ru-0.22
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - './nginx.conf:/etc/nginx/nginx.conf'
  #     - '/etc/letsencrypt:/etc/letsencrypt'
  #   depends_on:
  #     - api_server
  #     - scale_server
  #   networks:
  #     - dev

  # backend:
  #   build:
  #     context: ./backend
  #   networks:
  #     - dev

  # frontend:
  #   build:
  #     context: ./frontend
  #   networks:
  #     - dev