"""Change product table

Revision ID: 7e6bf0d0a05c
Revises: 74ff42a6eeef
Create Date: 2025-04-15 20:52:14.930315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6bf0d0a05c'
down_revision: Union[str, None] = '74ff42a6eeef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('energy_kcal', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('water_percent', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('protein_percent', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('fat_percent', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('carbohydrates_percent', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('saturatedfa_percent', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('cholesterol_mg', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('monodisaccharides_percen', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('starch_percent', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('fiber_percent', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('organicacids_percent', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('ash_percent', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('sodium_mg', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('potassium_mg', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('calcium_mg', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('magnesium_mg', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('phosphorus_mg', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('iron_mg', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('retinol_ug', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('betacarotene_ug', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('retinoleq_ug', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('tocopheroleq_mg', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('thiamine_mg', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('riboflavin_mg', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('niacin_mg', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('niacineq_mg', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('ascorbicacid_mg', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('polyunsaturatedfa_percent', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('ethanol_percent', sa.Integer(), nullable=False))
    op.drop_column('products', 'carbohydrates')
    op.drop_column('products', 'fats')
    op.drop_column('products', 'calories')
    op.drop_column('products', 'proteins')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('proteins', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('calories', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('fats', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('carbohydrates', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'ethanol_percent')
    op.drop_column('products', 'polyunsaturatedfa_percent')
    op.drop_column('products', 'ascorbicacid_mg')
    op.drop_column('products', 'niacineq_mg')
    op.drop_column('products', 'niacin_mg')
    op.drop_column('products', 'riboflavin_mg')
    op.drop_column('products', 'thiamine_mg')
    op.drop_column('products', 'tocopheroleq_mg')
    op.drop_column('products', 'retinoleq_ug')
    op.drop_column('products', 'betacarotene_ug')
    op.drop_column('products', 'retinol_ug')
    op.drop_column('products', 'iron_mg')
    op.drop_column('products', 'phosphorus_mg')
    op.drop_column('products', 'magnesium_mg')
    op.drop_column('products', 'calcium_mg')
    op.drop_column('products', 'potassium_mg')
    op.drop_column('products', 'sodium_mg')
    op.drop_column('products', 'ash_percent')
    op.drop_column('products', 'organicacids_percent')
    op.drop_column('products', 'fiber_percent')
    op.drop_column('products', 'starch_percent')
    op.drop_column('products', 'monodisaccharides_percen')
    op.drop_column('products', 'cholesterol_mg')
    op.drop_column('products', 'saturatedfa_percent')
    op.drop_column('products', 'carbohydrates_percent')
    op.drop_column('products', 'fat_percent')
    op.drop_column('products', 'protein_percent')
    op.drop_column('products', 'water_percent')
    op.drop_column('products', 'energy_kcal')
    # ### end Alembic commands ###
