"""add source_type_id to products

Revision ID: a80af7d2007b
Revises: 474cf5c7c4f1
Create Date: 2025-05-29 21:04:16.608317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80af7d2007b'
down_revision: Union[str, None] = '474cf5c7c4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Шаг 1: добавить колонку nullable
    op.add_column('products', sa.Column('source_type_id', sa.Integer(), nullable=True))

    # Шаг 2: задать значение по умолчанию для уже существующих записей
    op.execute("UPDATE products SET source_type_id = 1")  # или другое валидное значение

    # Шаг 3: сделать колонку NOT NULL
    op.alter_column('products', 'source_type_id', nullable=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'source_type_id')
    # ### end Alembic commands ###
