"""add added_by_user_id to products

Revision ID: b101700c53d9
Revises: a80af7d2007b
Create Date: 2025-05-29 21:49:24.393166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b101700c53d9'
down_revision: Union[str, None] = 'a80af7d2007b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('added_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['added_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'added_by_user_id')
    # ### end Alembic commands ###
