"""Add to Product nullable

Revision ID: fa6cf33f75d0
Revises: 7e6bf0d0a05c
Create Date: 2025-04-15 21:46:13.237445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6cf33f75d0'
down_revision: Union[str, None] = '7e6bf0d0a05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'energy_kcal',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'water_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'protein_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'fat_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'carbohydrates_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'saturatedfa_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'cholesterol_mg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'monodisaccharides_percen',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'starch_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'fiber_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'organicacids_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'ash_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'sodium_mg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'potassium_mg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'calcium_mg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'magnesium_mg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'phosphorus_mg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'iron_mg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'retinol_ug',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'betacarotene_ug',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'retinoleq_ug',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'tocopheroleq_mg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'thiamine_mg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'riboflavin_mg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'niacin_mg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'niacineq_mg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'ascorbicacid_mg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'polyunsaturatedfa_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'ethanol_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'ethanol_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'polyunsaturatedfa_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'ascorbicacid_mg',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'niacineq_mg',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'niacin_mg',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'riboflavin_mg',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'thiamine_mg',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'tocopheroleq_mg',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'retinoleq_ug',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'betacarotene_ug',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'retinol_ug',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'iron_mg',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'phosphorus_mg',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'magnesium_mg',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'calcium_mg',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'potassium_mg',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'sodium_mg',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'ash_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'organicacids_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'fiber_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'starch_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'monodisaccharides_percen',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'cholesterol_mg',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'saturatedfa_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'carbohydrates_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'fat_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'protein_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'water_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'energy_kcal',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
